### ISSUE TITLE
heroku bob build error

### ISSUE THREAD

**Issue by sharanraj124** [heroku-python/bob-builder#38] opened 2019-03-22 08:11 UTC
hi, we getting some error in bob build. I don't how to resolve this. pls support for this 
```
~ $ bob build support/build/extensions/no-debug-non-zts-20121212/atatus-1.6.1
Traceback (most recent call last):
  File "/app/.heroku/python/bin/bob", line 7, in <module>
    from bob import cli
  File "/app/.heroku/python/lib/python3.6/site-packages/bob/__init__.py", line 1, in <module>
    from . import cli
  File "/app/.heroku/python/lib/python3.6/site-packages/bob/cli.py", line 20, in <module>
    from .models import Formula
  File "/app/.heroku/python/lib/python3.6/site-packages/bob/models.py", line 33, in <module>
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/app/.heroku/python/lib/python3.6/os.py", line 1017, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
```

**Comment by dzuelke** [comment] 2019-03-23 21:17
Duplicate of #34

**Closed as completed by dzuelke** 2019-03-23 21:17 UTC
